name: SPE CI-CD

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2
      - name: Print the operating system (spoiler, it is ${{ runner.os }})
        run: echo ${{ runner.os }}
      - name: Print the project version
        run: ./gradlew printGitSemVer
      - name: Build with Gradle
        run: ./gradlew build --parallel
